trigger:
- master

jobs:
  - job: test_pwsh_ws2019
    displayName: 'Test Module with PowerShell 6 on Windows Server 2019'
    pool:
     name: 'Azure Pipelines'
     vmImage: windows-latest
    steps:
      - pwsh: .\test.ps1
        displayName: 'Run Tests'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/testResults.xml'
    mergeTestResults: true
    testRunTitle: 'PS7_WS2019'
